### ISSUE TITLE
Wget bad address?

### ISSUE THREAD

**Issue by Larry3best** [vladrevers/autopif#1]
When I run the manual check I get this output:
`Path to PIF file: /data/adb/modules/playintegrityfix/custom.pif.json
Start a once check.
Network is reachable.
Getting remote PIF file using get_pif_json.sh script.
wget: bad address 'sourceforge.net'
Failed to get remote PIF file.
Once check is skipped`

**Comment by vladrevers** [comment]
Hello, no, the address there is correct. After googling this error, it seems the problem might be with DNS. Try opening "sourceforge.net" in your browser and see if it opens normally.
Also, I'd like to clarify, are you using the official Magisk, some fork of it, or other rooting methods (APatch/KernelSU)?

**Comment by JingMatrix** [comment]
That is what happened when you run it with `root` user in Termux, try directly run

```
sudo bash /data/adb/modules/autopif/service.sh -o
```

**Comment by vladrevers** [comment]
Closing as the issue author is not responding.

If you have the same problem (while https://sourceforge.net opens in browser), please create a new issue or mention me here.
